### ISSUE TITLE
Demos on CodePen don't work in Firefox

### ISSUE THREAD

**Issue by dzhavat** [GoogleChromeLabs/houdini.how#128]
While the demos on the main https://houdini.how/ page work fine in Firefox, opening the same demos on CodePen (by clicking the "Demo" button) don't work as expected.

Example of a working demo:

![image](https://user-images.githubusercontent.com/1096332/101996314-a5a7c880-3cd1-11eb-8ed2-c12e97157ad8.png)

Demo on CodePen:

![image](https://user-images.githubusercontent.com/1096332/101996323-c53ef100-3cd1-11eb-9e83-77f6c7092135.png)

**Comment by nucliweb** [comment]
All the worklets on houdini.how can be seen fine with Firefox because we are using the polyfill to add support.

We cannot control this behavior in the demos (out of our scope), but we will take it into account to make it a requirement in future incorporations, thanks

**Comment by zhenyanghua** [comment]
I had similar issues earlier but then after some investigation, I found in addition to my CodePen demo not providing the polyfill, CodePen editor result pane seems to be painted before the worklet module is loaded when using polyfill, which causing the CodePen demo to not display the effect until code change or the resize of the result pane. 

To walk around the issue I described, I need to manually trigger a resize event after the module is loaded. 

[CodePen Demo](https://codepen.io/zhua/pen/LYRxxJK):

![image](https://user-images.githubusercontent.com/6165894/102039610-61333000-3d98-11eb-95c4-036f099b5753.png)

**Comment by dzhavat** [comment]
@nucliweb That makes sense. Thanks for the clarification. Feel free to close the issue if you think it will not result in any other action points.
